### PR TITLE
Unite source

### PR DESCRIPTION
**Pull request by ghost**
Added Unite source for Gulp tasks (#3). It is a very basic source similar to the CtrlP integration you already provide.

### CODE REVIEW

**Comment by KabbAmine** [comment]
Good, thanks for your work :smile:
I'll merge it after testing, next week I think.

**Comment by mhartington** [comment]
Pulled this down to give it a test, works really well! Nice job on this

**Comment by KabbAmine** [comment]
LGTM :+1: But can you please squash your commits into one and force push it.

**Comment by ghost** [comment]
Thanks guys. Squashed and pushed (bare with me as I am just getting into GH)

**Comment by KabbAmine** [comment]
Nice work, thanks for your contribution.

**Pull request merged**
